version: "3"

services:
  swift-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - 3306:3306
  swift-rest-ui:
    image: dockerreg.training.local:5000/swift-rest-ui
    depends_on:
      - swift-mysql
    ports:
      - 8080:8080
    environment:
      DBHOST: swift-mysql
      DBNAME: ${DBNAME}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
