version: "3"

services:
  swift_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - 3306:3306
  swift_test_app:
    image: swift_test_app
    depends_on:
      - swift_mysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DBHOST}:3306/${DBNAME}?useSSL=false
      DATABASE_USER: ${USERNAME}
      DATABASE_PASSWORD: ${PASSWORD}
