version: "3"

services:
  docker_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swift
      MYSQL_PASSWORD: root
  swift_test_app:
    image: swift_test_app
    depends-on:
      - docker_mysql
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/swift?useSSL=false