version: "3"

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=swift
      - MYSQL_PASSWORD=root
  swift-app:
    image: swift-app
    depends-on:
      - docker-mysql
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=swift
      - DATABASE_PORT=3306